name: CI/CD Pipeline

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.2

    - name: Setup Node.js
      uses: actions/setup-node@v2.4.2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Build Angular App
      run: ng build

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.MY_GITHUB_TOKEN }}
        publish_dir: ./docs/<your-project-name>

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
